name: overs
description: Application for detecting over 2.5 goals fixtures

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=3.0.1"

dependencies:
  country_icons: ^2.0.2
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  http: ^0.13.4
  path_provider: ^2.0.11
  provider: ^6.0.3

dev_dependencies:
  dart_code_metrics: ^4.15.2
  flutter_test:
    sdk: flutter
  very_good_analysis: ^3.0.0

flutter:
  uses-material-design: true